name:                musicround1
version:             0.1.0.0
github:              "githubuser/musicround1"
license:             BSD3
author:              "Hugo O. Rivera Calzadillas"
maintainer:          "hugo@roguh.com"
copyright:           "2022 Hugo O. Rivera Calzadillas"

extra-source-files:
- README.markdown
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.markdown file.
description:         Please see the README on GitHub at <https://github.com/githubuser/musicround1#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea >= 2
- markdown-unlit >= 0.5.1 && < 1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  musicround1-exe:
    main:                Main.lhs
    source-dirs:         app
    ghc-options:
    - -pgmL markdown-unlit
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicround1

tests:
  musicround1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicround1
