#!/bin/sh
FILES="${FILES:-samples}"
MAX_ITERATIONS="${MAX_ITERATIONS:-100}"

set -e
# Run a cool default first
# "$(dirname "$0")"/gameoflife.py \
#   --pretty --color on --delay 0.07 --glider --iterations "$MAX_ITERATIONS" $@

while true; do
for file in $(find "$FILES" -type f -iname *.txt | shuf); do
  "$(dirname "$0")"/gameoflife.py \
    --pretty --color on --delay 0.07 \
    --file "$file" --expand-to-size --iterations "$MAX_ITERATIONS" \
    $@
done
done
