#!/bin/sh
BASE="$(dirname "$0")"
DELAY="${DELAY:-0.02}"
FILES="${FILES:-$BASE/samples}"
MAX_ITERATIONS="${MAX_ITERATIONS:-300}"

# Allow the user to skip to next by pressing Ctrl-C
# set -e

while true; do
  # Shuffle file order each loop
  for file in $(find "$FILES" -type f -iname *.txt | shuf); do
    "$BASE/gameoflife.py" \
      --file "$file" \
      --pretty --color on --delay "$DELAY" \
      --expand-to-size \
      --iterations "$MAX_ITERATIONS" \
      $@
  done
  "$BASE/gameoflife.py" \
    --random \
    --pretty --color on --delay "$DELAY" \
    --expand-to-size \
    --iterations "$MAX_ITERATIONS" \
    $@

  # Give the user a chance to exit the while loop
  sleep 1 || exit 0
done
